name: light_control_app
description: اپ کنترل لامپ با ESP32
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.7.2
  http: 1.4.0
  speech_to_text: 7.0.0
  shared_preferences: 2.0.15
  flutter_lints: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true